(cl:defpackage depthai_ros_msgs-srv
  (:use )
  (:export
   "NORMALIZEDIMAGECROP"
   "<NORMALIZEDIMAGECROP-REQUEST>"
   "NORMALIZEDIMAGECROP-REQUEST"
   "<NORMALIZEDIMAGECROP-RESPONSE>"
   "NORMALIZEDIMAGECROP-RESPONSE"
   "TRIGGERNAMED"
   "<TRIGGERNAMED-REQUEST>"
   "TRIGGERNAMED-REQUEST"
   "<TRIGGERNAMED-RESPONSE>"
   "TRIGGERNAMED-RESPONSE"
  ))

