(cl:defpackage depthai_ros_msgs-msg
  (:use )
  (:export
   "<AUTOFOCUSCTRL>"
   "AUTOFOCUSCTRL"
   "<HANDLANDMARK>"
   "HANDLANDMARK"
   "<HANDLANDMARKARRAY>"
   "HANDLANDMARKARRAY"
   "<SPATIALDETECTION>"
   "SPATIALDETECTION"
   "<SPATIALDETECTIONARRAY>"
   "SPATIALDETECTIONARRAY"
  ))

