# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from depthai_ros_msgs/AutoFocusCtrl.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class AutoFocusCtrl(genpy.Message):
  _md5sum = "57bd33867f64daa701fce3a114856f8f"
  _type = "depthai_ros_msgs/AutoFocusCtrl"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint8 AF_MODE_AUTO = 0
uint8 AF_MODE_MACRO = 1
uint8 AF_MODE_CONTINUOUS_VIDEO = 2
uint8 AF_MODE_CONTINUOUS_PICTURE = 3
uint8 AF_MODE_EDOF = 4

uint8 auto_focus_mode

bool trigger_auto_focus
"""
  # Pseudo-constants
  AF_MODE_AUTO = 0
  AF_MODE_MACRO = 1
  AF_MODE_CONTINUOUS_VIDEO = 2
  AF_MODE_CONTINUOUS_PICTURE = 3
  AF_MODE_EDOF = 4

  __slots__ = ['auto_focus_mode','trigger_auto_focus']
  _slot_types = ['uint8','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       auto_focus_mode,trigger_auto_focus

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(AutoFocusCtrl, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.auto_focus_mode is None:
        self.auto_focus_mode = 0
      if self.trigger_auto_focus is None:
        self.trigger_auto_focus = False
    else:
      self.auto_focus_mode = 0
      self.trigger_auto_focus = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2B().pack(_x.auto_focus_mode, _x.trigger_auto_focus))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 2
      (_x.auto_focus_mode, _x.trigger_auto_focus,) = _get_struct_2B().unpack(str[start:end])
      self.trigger_auto_focus = bool(self.trigger_auto_focus)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2B().pack(_x.auto_focus_mode, _x.trigger_auto_focus))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 2
      (_x.auto_focus_mode, _x.trigger_auto_focus,) = _get_struct_2B().unpack(str[start:end])
      self.trigger_auto_focus = bool(self.trigger_auto_focus)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2B = None
def _get_struct_2B():
    global _struct_2B
    if _struct_2B is None:
        _struct_2B = struct.Struct("<2B")
    return _struct_2B
