// Generated by gencpp from file depthai_ros_msgs/HandLandmark.msg
// DO NOT EDIT!


#ifndef DEPTHAI_ROS_MSGS_MESSAGE_HANDLANDMARK_H
#define DEPTHAI_ROS_MSGS_MESSAGE_HANDLANDMARK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose2D.h>
#include <geometry_msgs/Point.h>

namespace depthai_ros_msgs
{
template <class ContainerAllocator>
struct HandLandmark_
{
  typedef HandLandmark_<ContainerAllocator> Type;

  HandLandmark_()
    : label()
    , lm_score(0.0)
    , landmark()
    , position()
    , is_spatial(false)  {
    }
  HandLandmark_(const ContainerAllocator& _alloc)
    : label(_alloc)
    , lm_score(0.0)
    , landmark(_alloc)
    , position(_alloc)
    , is_spatial(false)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _label_type;
  _label_type label;

   typedef float _lm_score_type;
  _lm_score_type lm_score;

   typedef std::vector< ::geometry_msgs::Pose2D_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Pose2D_<ContainerAllocator> >::other >  _landmark_type;
  _landmark_type landmark;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _position_type;
  _position_type position;

   typedef uint8_t _is_spatial_type;
  _is_spatial_type is_spatial;





  typedef boost::shared_ptr< ::depthai_ros_msgs::HandLandmark_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::depthai_ros_msgs::HandLandmark_<ContainerAllocator> const> ConstPtr;

}; // struct HandLandmark_

typedef ::depthai_ros_msgs::HandLandmark_<std::allocator<void> > HandLandmark;

typedef boost::shared_ptr< ::depthai_ros_msgs::HandLandmark > HandLandmarkPtr;
typedef boost::shared_ptr< ::depthai_ros_msgs::HandLandmark const> HandLandmarkConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::depthai_ros_msgs::HandLandmark_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::depthai_ros_msgs::HandLandmark_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::depthai_ros_msgs::HandLandmark_<ContainerAllocator1> & lhs, const ::depthai_ros_msgs::HandLandmark_<ContainerAllocator2> & rhs)
{
  return lhs.label == rhs.label &&
    lhs.lm_score == rhs.lm_score &&
    lhs.landmark == rhs.landmark &&
    lhs.position == rhs.position &&
    lhs.is_spatial == rhs.is_spatial;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::depthai_ros_msgs::HandLandmark_<ContainerAllocator1> & lhs, const ::depthai_ros_msgs::HandLandmark_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace depthai_ros_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::depthai_ros_msgs::HandLandmark_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::depthai_ros_msgs::HandLandmark_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::depthai_ros_msgs::HandLandmark_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::depthai_ros_msgs::HandLandmark_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::depthai_ros_msgs::HandLandmark_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::depthai_ros_msgs::HandLandmark_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::depthai_ros_msgs::HandLandmark_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e126f09ad65617304665e31f1a5736de";
  }

  static const char* value(const ::depthai_ros_msgs::HandLandmark_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe126f09ad6561730ULL;
  static const uint64_t static_value2 = 0x4665e31f1a5736deULL;
};

template<class ContainerAllocator>
struct DataType< ::depthai_ros_msgs::HandLandmark_<ContainerAllocator> >
{
  static const char* value()
  {
    return "depthai_ros_msgs/HandLandmark";
  }

  static const char* value(const ::depthai_ros_msgs::HandLandmark_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::depthai_ros_msgs::HandLandmark_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"# Center of the \n"
"\n"
"string label\n"
"\n"
"# Landmarks score.\n"
"float32 lm_score\n"
"\n"
"geometry_msgs/Pose2D[] landmark\n"
"\n"
"geometry_msgs/Point position\n"
"bool is_spatial\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose2D\n"
"# Deprecated\n"
"# Please use the full 3D pose.\n"
"\n"
"# In general our recommendation is to use a full 3D representation of everything and for 2D specific applications make the appropriate projections into the plane for their calculations but optimally will preserve the 3D information during processing.\n"
"\n"
"# If we have parallel copies of 2D datatypes every UI and other pipeline will end up needing to have dual interfaces to plot everything. And you will end up with not being able to use 3D tools for 2D use cases even if they're completely valid, as you'd have to reimplement it with different inputs and outputs. It's not particularly hard to plot the 2D pose or compute the yaw error for the Pose message and there are already tools and libraries that can do this for you.\n"
"\n"
"\n"
"# This expresses a position and orientation on a 2D manifold.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 theta\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::depthai_ros_msgs::HandLandmark_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::depthai_ros_msgs::HandLandmark_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.label);
      stream.next(m.lm_score);
      stream.next(m.landmark);
      stream.next(m.position);
      stream.next(m.is_spatial);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct HandLandmark_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::depthai_ros_msgs::HandLandmark_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::depthai_ros_msgs::HandLandmark_<ContainerAllocator>& v)
  {
    s << indent << "label: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.label);
    s << indent << "lm_score: ";
    Printer<float>::stream(s, indent + "  ", v.lm_score);
    s << indent << "landmark[]" << std::endl;
    for (size_t i = 0; i < v.landmark.size(); ++i)
    {
      s << indent << "  landmark[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Pose2D_<ContainerAllocator> >::stream(s, indent + "    ", v.landmark[i]);
    }
    s << indent << "position: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
    s << indent << "is_spatial: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_spatial);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DEPTHAI_ROS_MSGS_MESSAGE_HANDLANDMARK_H
