// Generated by gencpp from file depthai_ros_msgs/NormalizedImageCrop.msg
// DO NOT EDIT!


#ifndef DEPTHAI_ROS_MSGS_MESSAGE_NORMALIZEDIMAGECROP_H
#define DEPTHAI_ROS_MSGS_MESSAGE_NORMALIZEDIMAGECROP_H

#include <ros/service_traits.h>


#include <depthai_ros_msgs/NormalizedImageCropRequest.h>
#include <depthai_ros_msgs/NormalizedImageCropResponse.h>


namespace depthai_ros_msgs
{

struct NormalizedImageCrop
{

typedef NormalizedImageCropRequest Request;
typedef NormalizedImageCropResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct NormalizedImageCrop
} // namespace depthai_ros_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::depthai_ros_msgs::NormalizedImageCrop > {
  static const char* value()
  {
    return "35d4b74aa140d5d6ce7c27c43314e948";
  }

  static const char* value(const ::depthai_ros_msgs::NormalizedImageCrop&) { return value(); }
};

template<>
struct DataType< ::depthai_ros_msgs::NormalizedImageCrop > {
  static const char* value()
  {
    return "depthai_ros_msgs/NormalizedImageCrop";
  }

  static const char* value(const ::depthai_ros_msgs::NormalizedImageCrop&) { return value(); }
};


// service_traits::MD5Sum< ::depthai_ros_msgs::NormalizedImageCropRequest> should match
// service_traits::MD5Sum< ::depthai_ros_msgs::NormalizedImageCrop >
template<>
struct MD5Sum< ::depthai_ros_msgs::NormalizedImageCropRequest>
{
  static const char* value()
  {
    return MD5Sum< ::depthai_ros_msgs::NormalizedImageCrop >::value();
  }
  static const char* value(const ::depthai_ros_msgs::NormalizedImageCropRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::depthai_ros_msgs::NormalizedImageCropRequest> should match
// service_traits::DataType< ::depthai_ros_msgs::NormalizedImageCrop >
template<>
struct DataType< ::depthai_ros_msgs::NormalizedImageCropRequest>
{
  static const char* value()
  {
    return DataType< ::depthai_ros_msgs::NormalizedImageCrop >::value();
  }
  static const char* value(const ::depthai_ros_msgs::NormalizedImageCropRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::depthai_ros_msgs::NormalizedImageCropResponse> should match
// service_traits::MD5Sum< ::depthai_ros_msgs::NormalizedImageCrop >
template<>
struct MD5Sum< ::depthai_ros_msgs::NormalizedImageCropResponse>
{
  static const char* value()
  {
    return MD5Sum< ::depthai_ros_msgs::NormalizedImageCrop >::value();
  }
  static const char* value(const ::depthai_ros_msgs::NormalizedImageCropResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::depthai_ros_msgs::NormalizedImageCropResponse> should match
// service_traits::DataType< ::depthai_ros_msgs::NormalizedImageCrop >
template<>
struct DataType< ::depthai_ros_msgs::NormalizedImageCropResponse>
{
  static const char* value()
  {
    return DataType< ::depthai_ros_msgs::NormalizedImageCrop >::value();
  }
  static const char* value(const ::depthai_ros_msgs::NormalizedImageCropResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DEPTHAI_ROS_MSGS_MESSAGE_NORMALIZEDIMAGECROP_H
