// Generated by gencpp from file depthai_ros_msgs/NormalizedImageCropResponse.msg
// DO NOT EDIT!


#ifndef DEPTHAI_ROS_MSGS_MESSAGE_NORMALIZEDIMAGECROPRESPONSE_H
#define DEPTHAI_ROS_MSGS_MESSAGE_NORMALIZEDIMAGECROPRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace depthai_ros_msgs
{
template <class ContainerAllocator>
struct NormalizedImageCropResponse_
{
  typedef NormalizedImageCropResponse_<ContainerAllocator> Type;

  NormalizedImageCropResponse_()
    : status(0)  {
    }
  NormalizedImageCropResponse_(const ContainerAllocator& _alloc)
    : status(0)  {
  (void)_alloc;
    }



   typedef int64_t _status_type;
  _status_type status;





  typedef boost::shared_ptr< ::depthai_ros_msgs::NormalizedImageCropResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::depthai_ros_msgs::NormalizedImageCropResponse_<ContainerAllocator> const> ConstPtr;

}; // struct NormalizedImageCropResponse_

typedef ::depthai_ros_msgs::NormalizedImageCropResponse_<std::allocator<void> > NormalizedImageCropResponse;

typedef boost::shared_ptr< ::depthai_ros_msgs::NormalizedImageCropResponse > NormalizedImageCropResponsePtr;
typedef boost::shared_ptr< ::depthai_ros_msgs::NormalizedImageCropResponse const> NormalizedImageCropResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::depthai_ros_msgs::NormalizedImageCropResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::depthai_ros_msgs::NormalizedImageCropResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::depthai_ros_msgs::NormalizedImageCropResponse_<ContainerAllocator1> & lhs, const ::depthai_ros_msgs::NormalizedImageCropResponse_<ContainerAllocator2> & rhs)
{
  return lhs.status == rhs.status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::depthai_ros_msgs::NormalizedImageCropResponse_<ContainerAllocator1> & lhs, const ::depthai_ros_msgs::NormalizedImageCropResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace depthai_ros_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::depthai_ros_msgs::NormalizedImageCropResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::depthai_ros_msgs::NormalizedImageCropResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::depthai_ros_msgs::NormalizedImageCropResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::depthai_ros_msgs::NormalizedImageCropResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::depthai_ros_msgs::NormalizedImageCropResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::depthai_ros_msgs::NormalizedImageCropResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::depthai_ros_msgs::NormalizedImageCropResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4107476a6271fc2684d94be17d33f854";
  }

  static const char* value(const ::depthai_ros_msgs::NormalizedImageCropResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4107476a6271fc26ULL;
  static const uint64_t static_value2 = 0x84d94be17d33f854ULL;
};

template<class ContainerAllocator>
struct DataType< ::depthai_ros_msgs::NormalizedImageCropResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "depthai_ros_msgs/NormalizedImageCropResponse";
  }

  static const char* value(const ::depthai_ros_msgs::NormalizedImageCropResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::depthai_ros_msgs::NormalizedImageCropResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 status\n"
;
  }

  static const char* value(const ::depthai_ros_msgs::NormalizedImageCropResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::depthai_ros_msgs::NormalizedImageCropResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NormalizedImageCropResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::depthai_ros_msgs::NormalizedImageCropResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::depthai_ros_msgs::NormalizedImageCropResponse_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<int64_t>::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DEPTHAI_ROS_MSGS_MESSAGE_NORMALIZEDIMAGECROPRESPONSE_H
