// Generated by gencpp from file depthai_ros_msgs/SpatialDetectionArray.msg
// DO NOT EDIT!


#ifndef DEPTHAI_ROS_MSGS_MESSAGE_SPATIALDETECTIONARRAY_H
#define DEPTHAI_ROS_MSGS_MESSAGE_SPATIALDETECTIONARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <depthai_ros_msgs/SpatialDetection.h>

namespace depthai_ros_msgs
{
template <class ContainerAllocator>
struct SpatialDetectionArray_
{
  typedef SpatialDetectionArray_<ContainerAllocator> Type;

  SpatialDetectionArray_()
    : header()
    , detections()  {
    }
  SpatialDetectionArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , detections(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::depthai_ros_msgs::SpatialDetection_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::depthai_ros_msgs::SpatialDetection_<ContainerAllocator> >::other >  _detections_type;
  _detections_type detections;





  typedef boost::shared_ptr< ::depthai_ros_msgs::SpatialDetectionArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::depthai_ros_msgs::SpatialDetectionArray_<ContainerAllocator> const> ConstPtr;

}; // struct SpatialDetectionArray_

typedef ::depthai_ros_msgs::SpatialDetectionArray_<std::allocator<void> > SpatialDetectionArray;

typedef boost::shared_ptr< ::depthai_ros_msgs::SpatialDetectionArray > SpatialDetectionArrayPtr;
typedef boost::shared_ptr< ::depthai_ros_msgs::SpatialDetectionArray const> SpatialDetectionArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::depthai_ros_msgs::SpatialDetectionArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::depthai_ros_msgs::SpatialDetectionArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::depthai_ros_msgs::SpatialDetectionArray_<ContainerAllocator1> & lhs, const ::depthai_ros_msgs::SpatialDetectionArray_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.detections == rhs.detections;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::depthai_ros_msgs::SpatialDetectionArray_<ContainerAllocator1> & lhs, const ::depthai_ros_msgs::SpatialDetectionArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace depthai_ros_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::depthai_ros_msgs::SpatialDetectionArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::depthai_ros_msgs::SpatialDetectionArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::depthai_ros_msgs::SpatialDetectionArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::depthai_ros_msgs::SpatialDetectionArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::depthai_ros_msgs::SpatialDetectionArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::depthai_ros_msgs::SpatialDetectionArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::depthai_ros_msgs::SpatialDetectionArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f3caf8c6374b91f3a4b93f9610044116";
  }

  static const char* value(const ::depthai_ros_msgs::SpatialDetectionArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf3caf8c6374b91f3ULL;
  static const uint64_t static_value2 = 0xa4b93f9610044116ULL;
};

template<class ContainerAllocator>
struct DataType< ::depthai_ros_msgs::SpatialDetectionArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "depthai_ros_msgs/SpatialDetectionArray";
  }

  static const char* value(const ::depthai_ros_msgs::SpatialDetectionArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::depthai_ros_msgs::SpatialDetectionArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# A list of 2D detections, for a multi-object 2D detector along with 3D depth information.\n"
"\n"
"std_msgs/Header header\n"
"# A list of the detected proposals. A multi-proposal detector might generate along with the 3D depth information\n"
"#   this list with many candidate detections generated from a single input.\n"
"SpatialDetection[] detections\n"
"\n"
"## These messages are created as close as possible to the official vision_msgs(http://wiki.ros.org/vision_msgs)\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: depthai_ros_msgs/SpatialDetection\n"
"\n"
"# Class probabilities\n"
"vision_msgs/ObjectHypothesis[] results\n"
"\n"
"# 2D bounding box surrounding the object.\n"
"vision_msgs/BoundingBox2D bbox\n"
"\n"
"# Center of the detected object in meters \n"
"geometry_msgs/Point position\n"
"\n"
"# If true, this message contains object tracking information.\n"
"bool is_tracking\n"
"\n"
"# ID used for consistency across multiple detection messages. This value will\n"
"# likely differ from the id field set in each individual ObjectHypothesis.\n"
"# If you set this field, be sure to also set is_tracking to True.\n"
"string tracking_id\n"
"================================================================================\n"
"MSG: vision_msgs/ObjectHypothesis\n"
"# An object hypothesis that contains no position information.\n"
"\n"
"# The unique numeric ID of object detected. To get additional information about\n"
"#   this ID, such as its human-readable name, listeners should perform a lookup\n"
"#   in a metadata database. See vision_msgs/VisionInfo.msg for more detail.\n"
"int64 id\n"
"\n"
"# The probability or confidence value of the detected object. By convention,\n"
"#   this value should lie in the range [0-1].\n"
"float64 score\n"
"================================================================================\n"
"MSG: vision_msgs/BoundingBox2D\n"
"# A 2D bounding box that can be rotated about its center.\n"
"# All dimensions are in pixels, but represented using floating-point\n"
"#   values to allow sub-pixel precision. If an exact pixel crop is required\n"
"#   for a rotated bounding box, it can be calculated using Bresenham's line\n"
"#   algorithm.\n"
"\n"
"# The 2D position (in pixels) and orientation of the bounding box center.\n"
"geometry_msgs/Pose2D center\n"
"\n"
"# The size (in pixels) of the bounding box surrounding the object relative\n"
"#   to the pose of its center.\n"
"float64 size_x\n"
"float64 size_y\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose2D\n"
"# Deprecated\n"
"# Please use the full 3D pose.\n"
"\n"
"# In general our recommendation is to use a full 3D representation of everything and for 2D specific applications make the appropriate projections into the plane for their calculations but optimally will preserve the 3D information during processing.\n"
"\n"
"# If we have parallel copies of 2D datatypes every UI and other pipeline will end up needing to have dual interfaces to plot everything. And you will end up with not being able to use 3D tools for 2D use cases even if they're completely valid, as you'd have to reimplement it with different inputs and outputs. It's not particularly hard to plot the 2D pose or compute the yaw error for the Pose message and there are already tools and libraries that can do this for you.\n"
"\n"
"\n"
"# This expresses a position and orientation on a 2D manifold.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 theta\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::depthai_ros_msgs::SpatialDetectionArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::depthai_ros_msgs::SpatialDetectionArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.detections);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SpatialDetectionArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::depthai_ros_msgs::SpatialDetectionArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::depthai_ros_msgs::SpatialDetectionArray_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "detections[]" << std::endl;
    for (size_t i = 0; i < v.detections.size(); ++i)
    {
      s << indent << "  detections[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::depthai_ros_msgs::SpatialDetection_<ContainerAllocator> >::stream(s, indent + "    ", v.detections[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // DEPTHAI_ROS_MSGS_MESSAGE_SPATIALDETECTIONARRAY_H
