// Generated by gencpp from file depthai_ros_msgs/TriggerNamedRequest.msg
// DO NOT EDIT!


#ifndef DEPTHAI_ROS_MSGS_MESSAGE_TRIGGERNAMEDREQUEST_H
#define DEPTHAI_ROS_MSGS_MESSAGE_TRIGGERNAMEDREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace depthai_ros_msgs
{
template <class ContainerAllocator>
struct TriggerNamedRequest_
{
  typedef TriggerNamedRequest_<ContainerAllocator> Type;

  TriggerNamedRequest_()
    : name()  {
    }
  TriggerNamedRequest_(const ContainerAllocator& _alloc)
    : name(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;





  typedef boost::shared_ptr< ::depthai_ros_msgs::TriggerNamedRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::depthai_ros_msgs::TriggerNamedRequest_<ContainerAllocator> const> ConstPtr;

}; // struct TriggerNamedRequest_

typedef ::depthai_ros_msgs::TriggerNamedRequest_<std::allocator<void> > TriggerNamedRequest;

typedef boost::shared_ptr< ::depthai_ros_msgs::TriggerNamedRequest > TriggerNamedRequestPtr;
typedef boost::shared_ptr< ::depthai_ros_msgs::TriggerNamedRequest const> TriggerNamedRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::depthai_ros_msgs::TriggerNamedRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::depthai_ros_msgs::TriggerNamedRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::depthai_ros_msgs::TriggerNamedRequest_<ContainerAllocator1> & lhs, const ::depthai_ros_msgs::TriggerNamedRequest_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::depthai_ros_msgs::TriggerNamedRequest_<ContainerAllocator1> & lhs, const ::depthai_ros_msgs::TriggerNamedRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace depthai_ros_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::depthai_ros_msgs::TriggerNamedRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::depthai_ros_msgs::TriggerNamedRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::depthai_ros_msgs::TriggerNamedRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::depthai_ros_msgs::TriggerNamedRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::depthai_ros_msgs::TriggerNamedRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::depthai_ros_msgs::TriggerNamedRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::depthai_ros_msgs::TriggerNamedRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c1f3d28f1b044c871e6eff2e9fc3c667";
  }

  static const char* value(const ::depthai_ros_msgs::TriggerNamedRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc1f3d28f1b044c87ULL;
  static const uint64_t static_value2 = 0x1e6eff2e9fc3c667ULL;
};

template<class ContainerAllocator>
struct DataType< ::depthai_ros_msgs::TriggerNamedRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "depthai_ros_msgs/TriggerNamedRequest";
  }

  static const char* value(const ::depthai_ros_msgs::TriggerNamedRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::depthai_ros_msgs::TriggerNamedRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n"
;
  }

  static const char* value(const ::depthai_ros_msgs::TriggerNamedRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::depthai_ros_msgs::TriggerNamedRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TriggerNamedRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::depthai_ros_msgs::TriggerNamedRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::depthai_ros_msgs::TriggerNamedRequest_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DEPTHAI_ROS_MSGS_MESSAGE_TRIGGERNAMEDREQUEST_H
