// Generated by gencpp from file depthai_ros_msgs/TriggerNamed.msg
// DO NOT EDIT!


#ifndef DEPTHAI_ROS_MSGS_MESSAGE_TRIGGERNAMED_H
#define DEPTHAI_ROS_MSGS_MESSAGE_TRIGGERNAMED_H

#include <ros/service_traits.h>


#include <depthai_ros_msgs/TriggerNamedRequest.h>
#include <depthai_ros_msgs/TriggerNamedResponse.h>


namespace depthai_ros_msgs
{

struct TriggerNamed
{

typedef TriggerNamedRequest Request;
typedef TriggerNamedResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TriggerNamed
} // namespace depthai_ros_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::depthai_ros_msgs::TriggerNamed > {
  static const char* value()
  {
    return "d82dc6474dd88dad5e1615ab1b2ca74c";
  }

  static const char* value(const ::depthai_ros_msgs::TriggerNamed&) { return value(); }
};

template<>
struct DataType< ::depthai_ros_msgs::TriggerNamed > {
  static const char* value()
  {
    return "depthai_ros_msgs/TriggerNamed";
  }

  static const char* value(const ::depthai_ros_msgs::TriggerNamed&) { return value(); }
};


// service_traits::MD5Sum< ::depthai_ros_msgs::TriggerNamedRequest> should match
// service_traits::MD5Sum< ::depthai_ros_msgs::TriggerNamed >
template<>
struct MD5Sum< ::depthai_ros_msgs::TriggerNamedRequest>
{
  static const char* value()
  {
    return MD5Sum< ::depthai_ros_msgs::TriggerNamed >::value();
  }
  static const char* value(const ::depthai_ros_msgs::TriggerNamedRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::depthai_ros_msgs::TriggerNamedRequest> should match
// service_traits::DataType< ::depthai_ros_msgs::TriggerNamed >
template<>
struct DataType< ::depthai_ros_msgs::TriggerNamedRequest>
{
  static const char* value()
  {
    return DataType< ::depthai_ros_msgs::TriggerNamed >::value();
  }
  static const char* value(const ::depthai_ros_msgs::TriggerNamedRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::depthai_ros_msgs::TriggerNamedResponse> should match
// service_traits::MD5Sum< ::depthai_ros_msgs::TriggerNamed >
template<>
struct MD5Sum< ::depthai_ros_msgs::TriggerNamedResponse>
{
  static const char* value()
  {
    return MD5Sum< ::depthai_ros_msgs::TriggerNamed >::value();
  }
  static const char* value(const ::depthai_ros_msgs::TriggerNamedResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::depthai_ros_msgs::TriggerNamedResponse> should match
// service_traits::DataType< ::depthai_ros_msgs::TriggerNamed >
template<>
struct DataType< ::depthai_ros_msgs::TriggerNamedResponse>
{
  static const char* value()
  {
    return DataType< ::depthai_ros_msgs::TriggerNamed >::value();
  }
  static const char* value(const ::depthai_ros_msgs::TriggerNamedResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DEPTHAI_ROS_MSGS_MESSAGE_TRIGGERNAMED_H
